[package]
name = "nightcycle/model-util"
description = "A model utility!"
version = "1.0.1"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
MeshUtil = "nightcycle/mesh-util@^1.0.3"